version: '3'

services:
  backend:
    image: emp-backend
    build: ./backend
    ports:
      - "5050:5050"

  frontend:
    image: nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html 
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
