# Use the official Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /mainapp

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install necessary system packages and Python dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the rest of the application code into the container
COPY . .

# Expose the port on which the app will run
EXPOSE 8000

# Command to run the FastAPI app using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
