name: Run backend and frontend in EC2

on: 
#   push:
#     branches:
#       - master
  workflow_dispatch:

jobs:
    connct_EC2:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: List All items in root
              run: ls -a
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
            - name: Copy Files to EC2
              run: scp -r -o StrictHostKeyChecking=no ./your-local-directory/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/.

            - name: Create env file and check files in EC2
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                  echo 'DB_HOST=${{ secrets.DB_HOST }}' > /home/.env
                  ls -a /home
                  EOF
            
            - name: Install Nginx in EC2
              run: |
                    ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    sudo apt update
                    sudo apt install -y nginx
                    sudo systemctl start nginx
                    sudo systemctl enable nginx
                    EOF

            - name: Copy Nginx configuration file to EC2
              run: scp -r -o StrictHostKeyChecking=no ./nginx.conf ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/etc/nginx/sites-available/.

            - name: Start backend in EC2
              run: |
                    ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    cd backend
                    npm install
                    node server.js
                    EOF

            - name: Start frontend in EC2
              run: |
                    ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    cd frontend
                    npm install
                    npm start
                    EOF